### PR TITLE
Add AndroidANSI support.

### PR DESCRIPTION
**Pull request by Fox2Code**
I did my best to follow your coding style, also I had up update AndroidANSI a lot during the making of this pr.

Version before I started working on MRepo was `1.0.1`: https://github.com/Fox2Code/AndroidANSI/releases

And off course I wrote a base module: [AnsiRainbow.zip](https://github.com/ya0211/MRepo/files/11391185/AnsiRainbow.zip)

It's based on the FoxMMM rainbow module.

And off course a screenshot of the rainbow module:

[](https://user-images.githubusercontent.com/42963271/236049023-94459216-3046-454f-addd-a88c579c5830.png)

### CODE REVIEW

**Comment by Fox2Code** [comment]
"Merging is blocked
The base branch requires all commits to be signed."
BRUH, I have to battle with my health issues enough.
If I wasn't addicted to making code I wouldn't be able to contribute.

USE: https://github.com/ya0211/MRepo/commit/ece2bd9d79bc9eb6fbbd6f8f2ede83ed93db5ef2.patch
Then git apply as a patch if it not good enough and you can sign the commit yourself.

It's my bed time, and I don't have enough energy to allow me to spend time on signing commits, and it's about to end up on me having a panic attack or being so exhausted that I'm frozen in place in front of my computer doing nothing.

I already tried to setup commit signing in the past and failed.

**Comment by ya0211** [comment]
### Why I don't want this?
Firstly the module doesn't need to print a lot of things, secondly if the module forcefully requests `ANSI_SUPPORT` then it will lose support for Magisk App, even if it's not forcefully, that would require `two customize.sh`
 to support different managers, which would be unnecessary trouble.

I think this will split Magisk Module (Original Magisk Module & ANSI Magisk Module), I wish MRepo to be a util for Magisk, but not a must. MRepo lives for Magisk and will not break `upstream rules`.

If only for custom print, I don't think ANSI will be implemented.

**Comment by Fox2Code** [comment]
So the step 1 is upstream to regular Magisk.
The step 2 is upstream here with signed commits when I done it.

If theses two step are complete, would you accept my changes?

As I need to focus on my health first it will be quite some time before all of that is done.

Also I wanted to do signed commit for a long time, don't worry I'll figure out how to do when I'm better.

**Comment by Fox2Code** [comment]
Also I started making a sh library detecting ANSI support and using it or not depending on available support.

```bash
if [ "$ANSI_SUPPORT" == "true" ]; then
  ESC=""
  RED="$ESC[91m"
  ORANGE="$ESC[33m"
  YELLOW="$ESC[93m"
  GREEN="$ESC[92m"
  CYAN="$ESC[96m"
  BLUE="$ESC[94m"
  PURPLE="$ESC[95m"
  RESET="$ESC[0m"
else
  ESC=""
  RED=""
  ORANGE=""
  YELLOW=""
  GREEN=""
  CYAN=""
  BLUE=""
  PURPLE=""
  RESET=""
fi

```

**Comment by Fox2Code** [comment]
Also `AnsiConstants.ANSI_CMD_SUPPORT` is just `export ANSI_SUPPORT=true` specifically to express ANSI support.

code in `AnsiConstants` is [`public static final String ANSI_CMD_SUPPORT = "export ANSI_SUPPORT=true";`](https://github.com/Fox2Code/AndroidANSI/blob/master/library/src/main/java/com/fox2code/androidansi/AnsiConstants.java#LL13C78-L13C78)

I thought about module fragmentation and I didn't want modules that use ANSI to require it too.
I consider not checking `ANSI_SUPPORT` a failure of usage of my library by modules.

**Comment by Fox2Code** [comment]
Also for the v2 of this PR, when Magisk has ANSI support, I'll add a toggle in settings that disable ANSI support. 
Dont worry about it! :3

I'll convert this to a draft, since it's clearly not ready for MRepo use and I need to make some changes before it's good enough for MRepo.

**Comment by Fox2Code** [comment]
I sorted out the signature problem, all my commits are now signed.

I will try to do a similar upstream to the Magisk app.

**Comment by Fox2Code** [comment]
Honestly, I did all I could to make it better, I'll reopen this a ready for review because I need to take care of my health first, just close it with everything that needs to change for you to accept it, I'll try to make a PR to Magisk too when my health will allow me to do so.

**Comment by ya0211** [comment]
I will wait for the result from Magisk App, this PR will not be closed during this period. Of course your health is the priority.

**Pull request closed without merging**
